### ISSUE TITLE
Questions about Data File

### ISSUE THREAD

**Issue by MuZiLiHui** [Lucky-Loek/ieee-phm-2012-data-challenge-dataset#1]
Excuse me,what is the difference between the file"FULL_TEST_SET" and "TEST_SET" ?

**Comment by Lucky-Loek** [comment]
Explanation is in the PDF file.

Basically the test set was cut off at random points, it's up to you to predict when the bearings are going to fail. The full test set consists of the complete measurement that were cut up to create the test set.
